"""assistant token expiry

Revision ID: e0002
Revises: e0001
Create Date: 2026-10-04 00:01:05.181903
"""
from datetime import datetime, timedelta, timezone

from alembic import op
import sqlalchemy as sa


revision = 'e0002'
down_revision = 'e0001'
branch_labels = None
depends_on = None


def upgrade():
    # Tokens issued before expiry existed get 30 days from the upgrade, then the column is required (fail closed).
    with op.batch_alter_table('assistant_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    stmt = sa.text("UPDATE assistant_tokens SET expires_at = :exp WHERE expires_at IS NULL").bindparams(
        sa.bindparam("exp", type_=sa.DateTime(timezone=True)))
    op.get_bind().execute(stmt, {"exp": datetime.now(timezone.utc) + timedelta(days=30)})
    with op.batch_alter_table('assistant_tokens', schema=None) as batch_op:
        batch_op.alter_column('expires_at', existing_type=sa.DateTime(timezone=True), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_tokens', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
