"""edge initial schema

Revision ID: e0001
Revises: 
Create Date: 2026-10-03 23:36:39.809979
"""
from alembic import op
import sqlalchemy as sa


revision = 'e0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('challenge', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('binding', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('expires', sa.Float(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('challenge')
    )
    op.create_table('edge_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('email_queued', sa.Boolean(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edge_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edge_notifications_job_id'), ['job_id'], unique=False)

    op.create_table('edge_users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('estate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('actor', sa.String(length=40), nullable=False),
    sa.Column('event', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('prev', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_audit_job_id'), ['job_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('wo_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('ticket', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=4), nullable=False),
    sa.Column('work_order', sa.JSON(), nullable=False),
    sa.Column('work_order_env', sa.JSON(), nullable=True),
    sa.Column('listing_facts', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=False),
    sa.Column('provider_statement', sa.JSON(), nullable=True),
    sa.Column('receipt', sa.JSON(), nullable=True),
    sa.Column('seeded_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wo_id')
    )
    op.create_table('seen_nonces',
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('seen_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('nonce')
    )
    op.create_table('transparency',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('record_digest', sa.String(length=64), nullable=False),
    sa.Column('prev', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('assistant_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['edge_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('changes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('op', sa.String(length=80), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('command_hash', sa.String(length=64), nullable=False),
    sa.Column('before_digest', sa.String(length=64), nullable=False),
    sa.Column('after_digest', sa.String(length=64), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_changes_job_id'), ['job_id'], unique=False)

    op.create_table('edge_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['edge_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('enrolments',
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['edge_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code_hash')
    )
    op.create_table('passkeys',
    sa.Column('credential_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['edge_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('credential_id')
    )
    with op.batch_alter_table('passkeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passkeys_user_id'), ['user_id'], unique=False)

    op.create_table('stepups',
    sa.Column('command_hash', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('op', sa.String(length=80), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approvals', sa.JSON(), nullable=False),
    sa.Column('created', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('command_hash')
    )
    with op.batch_alter_table('stepups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stepups_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stepups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stepups_job_id'))

    op.drop_table('stepups')
    with op.batch_alter_table('passkeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passkeys_user_id'))

    op.drop_table('passkeys')
    op.drop_table('enrolments')
    op.drop_table('edge_sessions')
    with op.batch_alter_table('changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_changes_job_id'))

    op.drop_table('changes')
    op.drop_table('assistant_tokens')
    op.drop_table('transparency')
    op.drop_table('seen_nonces')
    op.drop_table('jobs')
    with op.batch_alter_table('job_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_audit_job_id'))

    op.drop_table('job_audit')
    op.drop_table('estate')
    op.drop_table('edge_users')
    with op.batch_alter_table('edge_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edge_notifications_job_id'))

    op.drop_table('edge_notifications')
    op.drop_table('challenges')
    # ### end Alembic commands ###
