"""m2 providers verification agents services

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 22:17:00.160500
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revocations',
    sa.Column('item', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('item')
    )
    op.create_table('agents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('card', sa.JSON(), nullable=False),
    sa.Column('countersig', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_org_id'), ['org_id'], unique=False)

    op.create_table('credentials',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('envelope', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_reason', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credentials_org_id'), ['org_id'], unique=False)

    op.create_table('evidence_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=False),
    sa.Column('expires_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_items_org_id'), ['org_id'], unique=False)

    op.create_table('provider_keys',
    sa.Column('kid', sa.String(length=80), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('public_key', sa.String(length=100), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kid')
    )
    with op.batch_alter_table('provider_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_keys_org_id'), ['org_id'], unique=False)

    op.create_table('provider_profiles',
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('website', sa.String(length=300), nullable=False),
    sa.Column('contact_email', sa.String(length=254), nullable=False),
    sa.Column('review_note', sa.String(length=1000), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('services',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('level', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('price_text', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_org_id'))
        batch_op.drop_index(batch_op.f('ix_services_agent_id'))

    op.drop_table('services')
    op.drop_table('provider_profiles')
    with op.batch_alter_table('provider_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_keys_org_id'))

    op.drop_table('provider_keys')
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_items_org_id'))

    op.drop_table('evidence_items')
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credentials_org_id'))

    op.drop_table('credentials')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_org_id'))

    op.drop_table('agents')
    op.drop_table('revocations')
    # ### end Alembic commands ###
