"""m5 edges job index nonces

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 22:46:27.232598
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centre_nonces',
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('nonce')
    )
    op.create_table('customer_edges',
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=False),
    sa.Column('broker_kid', sa.String(length=80), nullable=False),
    sa.Column('broker_public_key', sa.String(length=100), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('job_index',
    sa.Column('wo_id', sa.String(length=40), nullable=False),
    sa.Column('customer_org_id', sa.String(length=32), nullable=False),
    sa.Column('provider_org_id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('edge_url', sa.String(length=300), nullable=False),
    sa.Column('level', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('changes_count', sa.Integer(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('receipt_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('wo_id')
    )
    with op.batch_alter_table('job_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_index_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_index_customer_org_id'), ['customer_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_index_provider_org_id'), ['provider_org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_index_provider_org_id'))
        batch_op.drop_index(batch_op.f('ix_job_index_customer_org_id'))
        batch_op.drop_index(batch_op.f('ix_job_index_agent_id'))

    op.drop_table('job_index')
    op.drop_table('customer_edges')
    op.drop_table('centre_nonces')
    # ### end Alembic commands ###
